<a href="https://colab.research.google.com/github/Prashantkumartalan43/Exercise/blob/main/python_basics_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Object Oriented Programming

class ClassName:
  pass

In [ ]:
class Customer:
  pass

customer1 = Customer()
print(customer1)

<__main__.Customer object at 0x7e5b421685c0>

In [ ]:
class Customer:
  name = "Rahul"

customer1 = Customer()
print(customer1.name)

Rahul

In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

In [ ]:
customer1 = Customer("Rahul")
customer2 = Customer("Amit")

print(customer1.name)
print(customer2.name)

Rahul
Amit

In [ ]:
class Customer:
  def __init__(self, name, city, purchase):
    self.name = name
    self.city = city
    self.purchase = purchase

In [ ]:
customer = Customer(
    "Rahul",
    "Delhi",
    50000
)

print(customer.name)
print(customer.city)
print(customer.purchase)

Rahul
Delhi
50000

In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

  def greet(self):
    print(f"Hello {self.name}")

customer = Customer("Rahul")
customer.greet()

Hello Rahul

In [ ]:
class Customer:
  def __init__(self, name, purchase):

    self.name = name
    self.purchase = purchase

  def customer_type(self):

    if self.purchase > 50000:
      return "Premium"

    return "Regular"

In [ ]:
customer = Customer("Rahul", 60000)

print(customer.customer_type())

Premium

In [ ]:
c1 = Customer("Rahul", 60000)
c2 = Customer("Amit", 72000)

In [ ]:
class Customer:
  def __init__(self, name, salary):

    self.name = name
    self.salary = salary

  def annual_salary(self):
    return self.salary * 12

c1 = Customer("Rahul", 50000)

print(c1.annual_salary())

600000

In [ ]:
class Product:
  def __init__(self, name, price):

    self.name = name
    self.price = price

  def discounted_price(self, discount):

    return(self.price * (1 - discount / 100))

In [ ]:
product = Product("Laptop", 50000)

print(product.discounted_price(10))

45000.0

In [ ]:
class SalesRecord:
  def __init__(self, month, sales):

    self.month = month
    self.sales = sales

  def display(self):

    print(self.month,
          self.sales)

record = SalesRecord("January", 15000)
print(record.display())

January 15000
None

In [ ]:
import math

In [ ]:
print(math.sqrt(25))

5.0

In [ ]:
radius = 5

area = math.pi * radius ** 2

print(f"{area:.2f}")

78.54

In [ ]:
import random

In [ ]:
print(random.randint(1, 10))

2

In [ ]:
import datetime

In [ ]:
today = datetime.date.today()

print(today)

2026-06-13

In [ ]:
now = datetime.datetime.now()

print(now)

2026-06-13 17:43:16.510316

In [ ]:
print(today.year)

2026

In [ ]:
customers = ["Rahul", "Amit", "Priya", "Neha"]

winner = random.choice(customers)

print(winner)

Rahul

In [ ]:
# numpy

pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np

In [ ]:
sales = [12000, 15000, 18000, 14000]

sales = np.array([12000, 15000, 18000, 14000])

print(sales)

[12000 15000 18000 14000]

In [ ]:
print(sales.shape)
print(sales.size)
print(sales.dtype)
print(sales.ndim)

(4,)
4
int64
1

In [ ]:
print(sales[0])
print(sales[-1])
print(sales[1:3])

12000
14000
[15000 18000]

In [ ]:
sales = np.array([100, 200, 300])

new_sales = sales * 2

print(new_sales)

[200 400 600]

In [ ]:
salaries = np.array([10000, 20000, 30000])

new_salaries = salaries * 1.2

print(new_salaries)

[12000. 24000. 36000.]

In [ ]:
print(np.sum(salaries))
print(np.mean(salaries))
print(np.min(salaries))
print(np.max(salaries))

60000
20000.0
10000
30000

In [ ]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]

In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(np.arange(1, 11, 2))
print(np.arange(2,11, 2))

[1 3 5 7 9]
[ 2  4  6  8 10]

In [ ]:
marks = np.array([[78,85,90],
                  [67,88,92],
                  [95,81,79]])

print(marks)

[[78 85 90]
 [67 88 92]
 [95 81 79]]

In [ ]:
print(marks.shape)
print(marks[0][1])
print(marks[0, 1])
print(f"{np.mean(marks):.2f}")

(3, 3)
85
85
83.89

In [ ]:
print(np.array(
    [1,2,"hello"]).dtype
)

<U21

In [ ]:
data = np.array([1,2,3,4,5,6])

print(data.shape)

(6,)

In [ ]:
data = data.reshape(2, 3)

print(data)
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

In [ ]:
print(data[:3])

[[1 2 3]
 [4 5 6]]

In [ ]:
print(data.ndim)
print(np.mean(data))

2
3.5

In [ ]:
print(np.sum(data))
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))

21
[5 7 9]
[ 6 15]

In [ ]:
import pandas as pd

In [ ]:
sales = pd.Series([12000, 15000, 18000, 14000])

print(sales)

0    12000
1    15000
2    18000
3    14000
dtype: int64

In [ ]:
data = {
    "Name": ["Rahul", "Amit", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age    City
0  Rahul   21   Delhi
1   Amit   22  Mumbai
2  Priya   20    Pune

In [ ]:
print(df.head(1))
print(df.tail(1))

    Name  Age   City
0  Rahul   21  Delhi
    Name  Age  City
2  Priya   20  Pune

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

In [ ]:
print(df.describe())

        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

In [ ]:
print(df["Name"])
print(df[["Name", "Age"]])

0    Rahul
1     Amit
2    Priya
Name: Name, dtype: object
    Name  Age
0  Rahul   21
1   Amit   22
2  Priya   20

In [ ]:
print(df.loc[0])

Name    Rahul
Age        21
City    Delhi
Name: 0, dtype: object

In [ ]:
print(df.iloc[1])

Name      Amit
Age         22
City    Mumbai
Name: 1, dtype: object

In [ ]:
data = {
    "Sales":[12000,15000,18000,14000]
}

df = pd.DataFrame(data)

In [ ]:
print(df["Sales"].sum())
print(df["Sales"].mean())
print(df["Sales"].min())
print(df["Sales"].max())

59000
14750.0
12000
18000

In [ ]:
df = pd.read_csv("sample_data/california_housing_test.csv")

print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0

   population  households  median_income  median_house_value
0      1537.0       606.0         6.6085            344700.0
1       809.0       277.0         3.5990            176500.0
2      1484.0       495.0         5.7934            270500.0
3        49.0        11.0         6.1359            330000.0
4       850.0       237.0         2.9375             81700.0

In [ ]:
import pandas as pd

data = {
    "Name": [
        "Rahul",
        "Amit",
        None,
        "Priya",
        "Rahul"
    ],

    "Age": [
        21,
        None,
        22,
        20,
        21
    ],

    "City": [
        "Delhi",
        "Mumbai",
        "Pune",
        None,
        "Delhi"
    ]
}

df = pd.DataFrame(data)

print(df)

    Name   Age    City
0  Rahul  21.0   Delhi
1   Amit   NaN  Mumbai
2   None  22.0    Pune
3  Priya  20.0    None
4  Rahul  21.0   Delhi

In [ ]:
print(df.isnull())

    Name    Age   City
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False  False

In [ ]:
print(df.isnull().sum())

Name    1
Age     1
City    1
dtype: int64

In [ ]:
clean_df = df.dropna()

print(clean_df)

    Name   Age   City
0  Rahul  21.0  Delhi
4  Rahul  21.0  Delhi

In [ ]:
df["Age"] = df["Age"].fillna(0)

In [ ]:
mean_age = df["Age"].mean()

df["Age"] = df["Age"].fillna(mean_age)

In [ ]:
df["City"] = df["City"].fillna(
    "Unknown"
)

In [ ]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
print(df.duplicated().sum())

1

In [ ]:
df = df.drop_duplicates()

In [ ]:
data = {
    "Name":[
        "Rahul",
        "Amit",
        "Priya"
    ],

    "Sales":[
        12000,
        18000,
        15000
    ]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print(
    df[
        df["Sales"] > 15000
    ]
)

   Name  Sales
1  Amit  18000

In [ ]:
filtered = df[
    (df["Sales"] >= 12000)
    &
    (df["Sales"] <= 17000)
]

print(filtered)

    Name  Sales
0  Rahul  12000
2  Priya  15000

In [ ]:
data = {
    "Sales":[
        18000,
        12000,
        21000,
        15000
    ]
}

In [ ]:
print(
    df.sort_values(
        by="Sales"
    )
)

    Name  Sales
0  Rahul  12000
2  Priya  15000
1   Amit  18000

In [ ]:
print(
    df.sort_values(
        by="Sales",
        ascending=False
    )
)

    Name  Sales
1   Amit  18000
2  Priya  15000
0  Rahul  12000

In [ ]:
df.rename(
    columns={
        "Name":"Customer_Name"
    },
    inplace=True
)

In [ ]:
print(df.dtypes)

Customer_Name    object
Sales             int64
dtype: object

In [ ]:
print("Rows:",
      len(df))

print("Missing:")
print(
    df.isnull().sum()
)

print("Duplicates:",
      df.duplicated().sum())

Rows: 3
Missing:
Customer_Name    0
Sales            0
dtype: int64
Duplicates: 0

In [ ]:
print("Rows:", len(df))

print("Missing:", df.isnull().sum())

print("Duplicates:", df.duplicated().sum())

Rows: 5
Missing: Name    1
Age     1
City    1
dtype: int64
Duplicates: 1

In [ ]:
df = (df.drop_duplicates())

print(df)

    Name   Age    City
0  Rahul  21.0   Delhi
1   Amit   NaN  Mumbai
2   None  22.0    Pune
3  Priya  20.0    None

In [ ]:
data = {
    "Customer":[
        "Rahul",
        "Amit",
        "Priya",
        "Rahul"
    ],

    "City":[
        "Delhi",
        None,
        "Pune",
        "Delhi"
    ],

    "Purchase":[
        50000,
        30000,
        None,
        50000
    ]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print("Missing:", df.isnull().sum())

df = df["City"].fillna("Unknown")

print(df)

Missing: Customer    0
City        1
Purchase    1
dtype: int64
0      Delhi
1    Unknown
2       Pune
3      Delhi
Name: City, dtype: object

In [ ]:
df = (df.drop_duplicates())

In [ ]:
import pandas as pd

data = {
    "Customer": [
        "Rahul",
        "Amit",
        "Priya",
        "Neha",
        "Vikas"
    ],

    "City": [
        "Delhi",
        "Mumbai",
        "Delhi",
        "Mumbai",
        "Delhi"
    ],

    "Purchase": [
        50000,
        30000,
        70000,
        40000,
        60000
    ]
}

df = pd.DataFrame(data)

print(df)

  Customer    City  Purchase
0    Rahul   Delhi     50000
1     Amit  Mumbai     30000
2    Priya   Delhi     70000
3     Neha  Mumbai     40000
4    Vikas   Delhi     60000

In [ ]:
city_sales = df.groupby("City")["Purchase"].sum().sort_values(ascending=True)

print(city_sales)

City
Mumbai     70000
Delhi     180000
Name: Purchase, dtype: int64

In [ ]:
city_avg = df.groupby("City")["Purchase"].mean()

print(city_avg)

City
Delhi     60000.0
Mumbai    35000.0
Name: Purchase, dtype: float64

In [ ]:
customer_count = df.groupby("City")["Customer"].count()

print(customer_count)

City
Delhi     3
Mumbai    2
Name: Customer, dtype: int64

In [ ]:
report = df.groupby("City")["Purchase"].describe()

print(report)

        count     mean           std      min      25%      50%      75%  \
City
Delhi     3.0  60000.0  10000.000000  50000.0  55000.0  60000.0  65000.0
Mumbai    2.0  35000.0   7071.067812  30000.0  32500.0  35000.0  37500.0

            max
City
Delhi   70000.0
Mumbai  40000.0

In [ ]:
data = {
    "City": [
        "Delhi",
        "Delhi",
        "Mumbai",
        "Mumbai"
    ],

    "Gender": [
        "Male",
        "Female",
        "Male",
        "Female"
    ],

    "Purchase": [
        50000,
        70000,
        30000,
        40000
    ]
}

df = pd.DataFrame(data)

In [ ]:
df.groupby(["City", "Gender"])["Purchase"].sum()

City    Gender
Delhi   Female    70000
        Male      50000
Mumbai  Female    40000
        Male      30000
Name: Purchase, dtype: int64

In [ ]:
print(df["City"].value_counts())

City
Delhi     2
Mumbai    2
Name: count, dtype: int64

In [ ]:
import pandas as pd

data = {
    "Department":[
        "HR",
        "IT",
        "IT",
        "HR"
    ],

    "Salary":[
        40000,
        60000,
        70000,
        45000
    ]
}

df = pd.DataFrame(data)

In [ ]:
report = df.groupby("Department")["Salary"].mean()

print(report)

Department
HR    42500.0
IT    65000.0
Name: Salary, dtype: float64

In [ ]:
import pandas as pd

data = {
    "Customer": [
        "Rahul", "Amit", "Priya", "Neha",
        "Vikas", "Riya", "Karan", "Sneha"
    ],
    "City": [
        "Delhi", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Delhi", "Pune", "Delhi"
    ],
    "Category": [
        "Electronics", "Furniture", "Electronics", "Furniture",
        "Office Supplies", "Electronics", "Furniture", "Office Supplies"
    ],
    "Sales": [
        50000, 30000, 70000, 25000,
        60000, 45000, 35000, 80000
    ],
    "Profit": [
        8000, -2000, 12000, 3000,
        9000, 7000, -1000, 15000
    ]
}

df = pd.DataFrame(data)

In [ ]:
df[df["City"] == "Delhi"]

  Customer   City         Category  Sales  Profit
0    Rahul  Delhi      Electronics  50000    8000
2    Priya  Delhi      Electronics  70000   12000
5     Riya  Delhi      Electronics  45000    7000
7    Sneha  Delhi  Office Supplies  80000   15000

In [ ]:
df[df["Sales"] > 50000]

  Customer    City         Category  Sales  Profit
2    Priya   Delhi      Electronics  70000   12000
4    Vikas  Mumbai  Office Supplies  60000    9000
7    Sneha   Delhi  Office Supplies  80000   15000

In [ ]:
df[df["Profit"] < 0]

  Customer    City   Category  Sales  Profit
1     Amit  Mumbai  Furniture  30000   -2000
6    Karan    Pune  Furniture  35000   -1000

In [ ]:
df[(df["Sales"] > 40000) & (df["City"] == 'Delhi')]

  Customer   City         Category  Sales  Profit
0    Rahul  Delhi      Electronics  50000    8000
2    Priya  Delhi      Electronics  70000   12000
5     Riya  Delhi      Electronics  45000    7000
7    Sneha  Delhi  Office Supplies  80000   15000

In [ ]:
df[["Customer", "Sales", "Profit"]]

  Customer  Sales  Profit
0    Rahul  50000    8000
1     Amit  30000   -2000
2    Priya  70000   12000
3     Neha  25000    3000
4    Vikas  60000    9000
5     Riya  45000    7000
6    Karan  35000   -1000
7    Sneha  80000   15000

In [ ]:
df["Customer"].str.startswith("R")

0     True
1    False
2    False
3    False
4    False
5     True
6    False
7    False
Name: Customer, dtype: bool

In [ ]:
df["Sales"].sort_values(ascending=False)

7    80000
2    70000
4    60000
0    50000
5    45000
6    35000
1    30000
3    25000
Name: Sales, dtype: int64

In [ ]:
df.groupby("Customer")["Sales"].max().sort_values(ascending=False).head(3)

Customer
Sneha    80000
Priya    70000
Vikas    60000
Name: Sales, dtype: int64

In [ ]:
average_sales = df["Sales"].mean()

In [ ]:
df[df["Sales"] > average_sales]

  Customer    City         Category  Sales  Profit
0    Rahul   Delhi      Electronics  50000    8000
2    Priya   Delhi      Electronics  70000   12000
4    Vikas  Mumbai  Office Supplies  60000    9000
7    Sneha   Delhi  Office Supplies  80000   15000

In [ ]:
df.groupby("Customer")["Profit"].max().sort_values(ascending=False).head(5)

Customer
Sneha    15000
Priya    12000
Vikas     9000
Rahul     8000
Riya      7000
Name: Profit, dtype: int64

In [ ]:
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Electronics        27000
Office Supplies    24000
Furniture              0
Name: Profit, dtype: int64

In [ ]:
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Electronics        165000
Office Supplies    140000
Furniture           90000
Name: Sales, dtype: int64

In [ ]:
df.groupby('City')['Sales'].sum().sort_values(ascending=False)

City
Delhi     245000
Mumbai     90000
Pune       60000
Name: Sales, dtype: int64

In [ ]:
df.groupby('Category')['Sales'].sum() > 100000

Category
Electronics         True
Furniture          False
Office Supplies     True
Name: Sales, dtype: bool

In [ ]:
def city_report(df):
  report = (df.groupby('City').agg(
      Orders = ('Customer', 'count'),
      Revenue = ('Sales', 'sum'),
      Profit = ('Profit', 'sum'),
      Average_sales = ('Sales', 'mean'),
      Highest_sale = ('Sales', 'max'),
      Lowest_sale = ('Sales', 'min')
      ).round(2)
  .reset_index()
    )
  return report

In [ ]:
report = city_report(df)

print(report)

     City  Orders  Revenue  Profit  Average_sales  Highest_sale  Lowest_sale
0   Delhi       4   245000   42000        61250.0         80000        45000
1  Mumbai       2    90000    7000        45000.0         60000        30000
2    Pune       2    60000    2000        30000.0         35000        25000

In [ ]:
def category_kpi(df, group_col):
  report = (
        df.groupby(group_col)
        .agg(
            Orders=("Customer", "count"),
            Revenue=("Sales", "sum"),
            Profit=("Profit", "sum"),
            Average_Sales=("Sales", "mean"),
            Highest_Sale=("Sales", "max"),
            Lowest_Sale=("Sales", "min")
        )
        .round(2)
        .reset_index()
    )
  return report

In [ ]:
city_report = category_kpi(df, "City")

print(city_report)

     City  Orders  Revenue  Profit  Average_Sales  Highest_Sale  Lowest_Sale
0   Delhi       4   245000   42000        61250.0         80000        45000
1  Mumbai       2    90000    7000        45000.0         60000        30000
2    Pune       2    60000    2000        30000.0         35000        25000

In [ ]:
category_report = category_kpi(df, "Category")

print(category_report)

          Category  Orders  Revenue  Profit  Average_Sales  Highest_Sale  \
0      Electronics       3   165000   27000        55000.0         70000
1        Furniture       3    90000       0        30000.0         35000
2  Office Supplies       2   140000   24000        70000.0         80000

   Lowest_Sale
0        45000
1        25000
2        60000

In [ ]:
def category_kpi(df, group_col, sort_by="Revenue", ascending=False):

    report = (
        df.groupby(group_col)
        .agg(
            Orders=("Customer", "count"),
            Revenue=("Sales", "sum"),
            Profit=("Profit", "sum"),
            Average_Sales=("Sales", "mean"),
            Highest_Sale=("Sales", "max"),
            Lowest_Sale=("Sales", "min")
        )
        .round(2)
        .sort_values(by=sort_by, ascending=ascending)
        .reset_index()
    )

    return report

In [ ]:
category_kpi(
    df,
    "City",
    sort_by="Profit"
)

     City  Orders  Revenue  Profit  Average_Sales  Highest_Sale  Lowest_Sale
0   Delhi       4   245000   42000        61250.0         80000        45000
1  Mumbai       2    90000    7000        45000.0         60000        30000
2    Pune       2    60000    2000        30000.0         35000        25000

In [ ]:
category_kpi(
    df,
    "Category",
    sort_by="Orders"
)

,Category,Orders,Revenue,Profit,Average_Sales,Highest_Sale,Lowest_Sale
0,Electronics,3,165000,27000,55000.0,70000,45000
1,Furniture,3,90000,0,30000.0,35000,25000
2,Office Supplies,2,140000,24000,70000.0,80000,60000

In [1]:
import pandas as pd

data = {
    "Customer":["Rahul","Amit","Priya","Neha","Vikas","Riya"],
    "Sales":[50000,30000,70000,25000,60000,45000],
    "Profit":[8000,3000,12000,-2000,9000,7000],
    "Category":[
        "Electronics",
        "Furniture",
        "Electronics",
        "Furniture",
        "Office Supplies",
        "Electronics"
    ]
}

df = pd.DataFrame(data)

In [ ]:
average_sales = df["Sales"].mean()

result = df[df["Sales"] > average_sales]

print(result)

  Customer  Sales  Profit         Category
0    Rahul  50000    8000      Electronics
2    Priya  70000   12000      Electronics
4    Vikas  60000    9000  Office Supplies

In [ ]:
average_profit = df["Profit"].mean()

result = df[df["Profit"] < average_profit]

print(result)

  Customer  Sales  Profit   Category
1     Amit  30000    3000  Furniture
3     Neha  25000   -2000  Furniture

In [ ]:
highest_sales = df[df["Sales"] == df["Sales"].max()]

print(highest_sales)

  Customer  Sales  Profit     Category
2    Priya  70000   12000  Electronics

In [ ]:
lowest_profit = df[df["Profit"] == df["Profit"].min()]

print(lowest_profit)

  Customer  Sales  Profit   Category
3     Neha  25000   -2000  Furniture

In [ ]:
def sales_category(sales):
    if sales >= 60000:
        return "High"
    elif sales >= 40000:
        return "Medium"
    else:
        return "Low"

df["Sales_Category"] = df["Sales"].apply(sales_category)

print(df)

  Customer  Sales  Profit         Category Sales_Category
0    Rahul  50000    8000      Electronics         Medium
1     Amit  30000    3000        Furniture            Low
2    Priya  70000   12000      Electronics           High
3     Neha  25000   -2000        Furniture            Low
4    Vikas  60000    9000  Office Supplies           High
5     Riya  45000    7000      Electronics         Medium

In [ ]:
def profit_status(profit):
    if profit < 0:
        return "Loss"
    else:
        return "Profit"

df["Profit_Status"] = df["Profit"].apply(profit_status)

print(df)

  Customer  Sales  Profit         Category Sales_Category Profit_Status
0    Rahul  50000    8000      Electronics         Medium        Profit
1     Amit  30000    3000        Furniture            Low        Profit
2    Priya  70000   12000      Electronics           High        Profit
3     Neha  25000   -2000        Furniture            Low          Loss
4    Vikas  60000    9000  Office Supplies           High        Profit
5     Riya  45000    7000      Electronics         Medium        Profit

In [ ]:
def customer_tier(sales):
    if sales >= 60000:
        return "Gold"
    elif sales >= 40000:
        return "Silver"
    else:
        return "Bronze"

df["Customer_Tier"] = df["Sales"].apply(customer_tier)

print(df)

  Customer  Sales  Profit         Category Sales_Category Profit_Status  \
0    Rahul  50000    8000      Electronics         Medium        Profit
1     Amit  30000    3000        Furniture            Low        Profit
2    Priya  70000   12000      Electronics           High        Profit
3     Neha  25000   -2000        Furniture            Low          Loss
4    Vikas  60000    9000  Office Supplies           High        Profit
5     Riya  45000    7000      Electronics         Medium        Profit

  Customer_Tier
0        Silver
1        Bronze
2          Gold
3        Bronze
4          Gold
5        Silver

In [ ]:
def classify_sales(df):

    df = df.copy()

    def sales_category(sales):
        if sales >= 60000:
            return "High"
        elif sales >= 40000:
            return "Medium"
        else:
            return "Low"

    def profit_status(profit):
        if profit < 0:
            return "Loss"
        else:
            return "Profit"

    def customer_tier(sales):
        if sales >= 60000:
            return "Gold"
        elif sales >= 40000:
            return "Silver"
        else:
            return "Bronze"

    df["Sales_Category"] = df["Sales"].apply(sales_category)
    df["Profit_Status"] = df["Profit"].apply(profit_status)
    df["Customer_Tier"] = df["Sales"].apply(customer_tier)

    return df

In [ ]:
result = classify_sales(df)

print(result)

  Customer  Sales  Profit         Category Sales_Category Profit_Status  \
0    Rahul  50000    8000      Electronics         Medium        Profit
1     Amit  30000    3000        Furniture            Low        Profit
2    Priya  70000   12000      Electronics           High        Profit
3     Neha  25000   -2000        Furniture            Low          Loss
4    Vikas  60000    9000  Office Supplies           High        Profit
5     Riya  45000    7000      Electronics         Medium        Profit

  Customer_Tier
0        Silver
1        Bronze
2          Gold
3        Bronze
4          Gold
5        Silver

In [2]:
import numpy as np

conditions = [
    df["Sales"] >= 60000,
    df["Sales"] >= 40000
]

choices = ["High", "Medium"]

df["Sales_Category"] = np.select(
    conditions,
    choices,
    default="Low"
)